### ISSUE TITLE
Build Lua without compat flags.

### ISSUE THREAD

**Issue by moteus** [ignacio/lua-appveyor-example#11]
I think by default Lua should build without compat flags. And there should be variable in appveyor.yml to turn on this.

See https://github.com/Tieske/luawinmake/issues/4

**Comment by ignacio** [comment]
Well, I prefer to respect what the makefile and common distros do by default. Lua 5.2.4 defines LUA_COMPAT_ALL and 5.3.0 defines LUA_COMPAT_5_2 by default in their makefiles (and the Debian package is also built that way) so you get a consistent behaviour in Linux and Windows.

An option should be provided to disable those flags, though. It will just add the --nocompat flag to the command line as @Tieske just added.
