### ISSUE TITLE
Current dir in LUA_PATH/LUA_CPATH

### ISSUE THREAD

**Issue by moteus** [ignacio/lua-appveyor-example#14]
Please add current path to search paths of Lua modules
`LUA_PATH=".\?.lua;.\?\init.lua"`
`LUA_CPATH=".\?.dll"`

**Comment by ignacio** [comment]
Do you mean [here](https://github.com/ignacio/lua-appveyor-example/blob/master/.appveyor/install.bat#L142)? If so, wouldn't it be better to do that in the test script instead?
Like:

~~~~lua
package.path = "./?.lua;./?/init.lua;"  .. package.path
package.cpath = "./?.dll;"  .. package.cpath
~~~~

This seems specific enough to no be set as default in the install scripts.

**Comment by moteus** [comment]
Lua by default has this path. Also after install luarocks on *nix this path also exists. So to constancy I think this is also exists on Windows as well.

**Comment by ignacio** [comment]
Oh, I see. I presume that calls to require in your test code are failing.
