### ISSUE TITLE
Make directory to external deps

### ISSUE THREAD

**Issue by moteus** [ignacio/lua-appveyor-example#6]
On Windows there no such thing but luarocks by default use `c:\external` to try find external deps for rocks.
I suggest that install scrip set global variable (e.g. `LR_EXTERNAL`) and makes empty directory tree.
%LR_EXTERNAL% - to install *.dll files (needs add this path to %PATH% variable)
%LR_EXTERNAL%\lib - to install *.lib files
%LR_EXTERNAL%\include - to install *.h files

make tree - https://github.com/moteus/lua-lcurl/blob/ci-appveyor/.appveyor/install.bat#L66-L72
install lib - https://github.com/moteus/lua-lcurl/blob/ci-appveyor/.appveyor/install_curl.bat#L30-L33

**Comment by ignacio** [comment]
What do you think would be best. Let the install script define LR_EXTERNAL or the appveyor.yml file do that? I'd go with setting that on th yml file.

**Comment by moteus** [comment]
If you can configure it it may be in appveyor.yml. But if install script do not set it then better it stay in install script.

**Comment by ignacio** [comment]
Ok, will set it in appveyor.yml and provide a default in the script.
