### ISSUE TITLE
Too long path

### ISSUE THREAD

**Issue by moteus** [ignacio/lua-appveyor-example#7]
This is not really your problem but after you set PATH env variable `appveyor` utility is not accessable any more (https://ci.appveyor.com/project/moteus/lua-lcurl/build/job/v70kn8skunrq044q)

```cmd
:: here we can use appveyor
echo **************************************
echo PATH1: %PATH%
appveyor AddMessage "End install Lua/LuaRocks"

set PATH=%NEW_PATH%
:: here  appveyor is not accessable
echo **************************************
echo PATH2: %PATH%
appveyor AddMessage "End install Lua/LuaRocks"
```

**Comment by ignacio** [comment]
I hit that problem yesterday, so I had to put Lua paths first. Since I'm not using appveyor executable anymore I didn't notice.

I tested [this workaround](http://www.cameronjtinker.com/post/2014/02/10/Windows-Path-Environment-Variable-Length.aspx) and it seems to be working.

**Comment by moteus** [comment]
You mean
```cmd
set PATH2=%PATH%
set PATH=%LUA_DIR%\bin;%PATH2%
```
?

**Comment by ignacio** [comment]
Yep. I'm testing that at the moment.

**Comment by ignacio** [comment]
Pretty sure this is the problem:

https://github.com/moteus/lua-lcurl/blob/d4d996cd7ae549b1086773d1ed91dc68db860172/.appveyor/install.bat#L169

Remove that whitespace between the ampersand and the caret: `set NEW_PATH=%PATH% & ^`

Can you confirm if it fixes the issue?

**Comment by moteus** [comment]
You are right. Sorry for this.
Now it works.

PS. You are not export LUA and LR_EXTERNAL variables this is why I start update this.

**Comment by ignacio** [comment]
No problem!
Will add those variables right away.
